    [env:d1_mini]
    platform = espressif8266
    board = d1_mini
    framework = arduino

    ; Serial Monitor
    monitor_speed = 115200


    build_flags =
        -I include
        -D DEBUG=1
        -D BAUD_RATE=115200

    board_build.filesystem = littlefs   ; Board filesystem
    ; OTA Upload 
    ; upload_protocol = espota
    ; upload_port = <fill later>

    ; lib_deps =
    ;     ArduinoJson
    ;     ESPAsyncWebServer